name: Actions 😎

on: workflow_dispatch

#permissions:
#  actions: read
#  contents: write
#  security-events: write
#  issues: write
#  pull-requests: write
#  repository-projects: write
#  id-token: write

jobs:
  Test:
    name: Test my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
            projectPath: ./Test-Project-2
            githubToken: ${{ secrets.GITHUB_TOKEN }}